Step 1: Import dependencies and Data 

In [119]:
#Import Libraries
import numpy as np
import pandas as pd

In [120]:
#Read Restaurant Profit Dara .csv file and divide the data into dependent and independent variables.
Main_data = pd.read_csv('/content/Restaurant_Profit_Data.csv')
Main_data.head()

Miscellaneous_Expenses  Food_Innovation_Spend  Advertising     City  \
0               138671.80              167497.20    475918.10  Chicago   
1               153151.59              164745.70    448032.53   Mumbai   
2               102919.55              155589.51    412068.54    Tokyo   
3               120445.85              146520.41    387333.62  Chicago   
4                93165.77              144255.34    370302.42    Tokyo   

      Profit  
0  202443.83  
1  201974.06  
2  201232.39  
3  193083.99  
4  176369.94

In [121]:
#Check the shape of the data
Main_data.shape

(50, 5)

Step 2: Data_Preprocessing

In [122]:
Main_data['City'].value_counts()

Chicago    17
Mumbai     17
Tokyo      16
Name: City, dtype: int64

In [123]:
city_dummies = pd.get_dummies(Main_data['City'])

In [124]:
city_dummies

Chicago  Mumbai  Tokyo
0         1       0      0
1         0       1      0
2         0       0      1
3         1       0      0
4         0       0      1
5         1       0      0
6         0       1      0
7         0       0      1
8         1       0      0
9         0       1      0
10        0       0      1
11        0       1      0
12        0       0      1
13        0       1      0
14        0       0      1
15        1       0      0
16        0       1      0
17        1       0      0
18        0       0      1
19        1       0      0
20        0       1      0
21        1       0      0
22        0       0      1
23        0       0      1
24        1       0      0
25        0       1      0
26        0       0      1
27        1       0      0
28        0       0      1
29        1       0      0
30        0       0      1
31        1       0      0
32        0       1      0
33        0       0      1
34        0       1      0
35        1       0      0
36        0       0      1
37        0       1      0
38        1       0      0
39        0       1      0
40        0       1      0
41        0       0      1
42        0       1      0
43        1       0      0
44        0       1      0
45        1       0      0
46        0       0      1
47        0       1      0
48        1       0      0
49        0       1      0

In [125]:
New_data = Main_data.join(city_dummies)

In [126]:
New_data.drop(['City'], axis = 1, inplace = True)

In [127]:
New_data.drop(['Tokyo'], axis = 1, inplace = True)

In [128]:
New_data.head()

Miscellaneous_Expenses  Food_Innovation_Spend  Advertising     Profit  \
0               138671.80              167497.20    475918.10  202443.83   
1               153151.59              164745.70    448032.53  201974.06   
2               102919.55              155589.51    412068.54  201232.39   
3               120445.85              146520.41    387333.62  193083.99   
4                93165.77              144255.34    370302.42  176369.94   

   Chicago  Mumbai  
0        1       0  
1        0       1  
2        0       0  
3        1       0  
4        0       0

In [129]:
#Create Feature Matrix and Dependent Variable Vector
New_data.drop(['Profit'], axis = 1, inplace = True)

In [130]:
New_data

Miscellaneous_Expenses  Food_Innovation_Spend  Advertising  Chicago  \
0                138671.80              167497.20    475918.10        1   
1                153151.59              164745.70    448032.53        0   
2                102919.55              155589.51    412068.54        0   
3                120445.85              146520.41    387333.62        1   
4                 93165.77              144255.34    370302.42        0   
5                101588.71              134024.90    366995.36        1   
6                148972.87              136763.46    131850.82        0   
7                147304.06              132446.13    328010.68        0   
8                150492.95              122690.52    315747.29        1   
9                110453.17              125482.88    309115.62        0   
10               112368.11              104061.08    233294.95        0   
11                93564.61              102819.96    253878.55        0   
12               129094.38               96011.75    253973.44        0   
13               137269.07               94140.39    256798.93        0   
14               158321.42              122091.24    260646.92        0   
15               124390.84              116671.61    265910.23        1   
16               123371.55               80161.11    268480.06        0   
17               146851.58               96805.16    286708.31        1   
18               115949.79               93897.16    299053.57        0   
19               155288.11               88567.70      4134.00        1   
20               115641.30               78401.86    302798.47        0   
21               155547.43               80537.47    303871.29        1   
22               124556.75               76142.56    307453.26        0   
23               107525.03               69680.53    308902.73        0   
24               101055.34               79192.01    144708.81        1   
25               141327.16               66812.71    142096.62        0   
26               145909.98               77476.87    138184.07        0   
27               129638.55               74255.60    357317.81        1   
28               184419.56               68199.52    122282.20        0   
29               154806.06               67753.48    111272.38        1   
30               117415.28               64142.48     95265.24        0   
31               154475.92               63284.38     92352.23        1   
32               130993.61               65556.86     50219.25        0   
33               104831.49               57641.95    218768.81        0   
34               159467.92               48574.07    214931.67        0   
35                86821.44               48162.02    209651.64        1   
36               128830.21               30811.76    205260.82        0   
37                53057.14               46217.95    201163.42        0   
38                67721.93               22377.59    189399.10        1   
39                84756.09               40706.51    179133.30        0   
40               120320.05               30902.33    176929.67        0   
41                86484.77               30040.92    168604.71        0   
42                97963.63               25788.93    152135.11        0   
43               129156.30               17653.73     39668.17        1   
44               156580.14               24325.74     32468.72        0   
45               125927.04                3148.23      6037.93        1   
46               117590.21                3463.46    301248.46        0   
47               137200.92                2148.00      4134.00        0   
48                53517.15                2690.05      4134.00        1   
49               118757.80                2148.00     49307.06        0   

    Mumbai  
0        0  
1        1  
2        0  
3        0  
4        0  
5        0  
6        1  
7        0  
8        0  
9        1  
10       0  
11       1  
12       

In [132]:
X = New_data.values

In [134]:
X.astype(int)

array([[138671, 167497, 475918,      1,      0],
       [153151, 164745, 448032,      0,      1],
       [102919, 155589, 412068,      0,      0],
       [120445, 146520, 387333,      1,      0],
       [ 93165, 144255, 370302,      0,      0],
       [101588, 134024, 366995,      1,      0],
       [148972, 136763, 131850,      0,      1],
       [147304, 132446, 328010,      0,      0],
       [150492, 122690, 315747,      1,      0],
       [110453, 125482, 309115,      0,      1],
       [112368, 104061, 233294,      0,      0],
       [ 93564, 102819, 253878,      0,      1],
       [129094,  96011, 253973,      0,      0],
       [137269,  94140, 256798,      0,      1],
       [158321, 122091, 260646,      0,      0],
       [124390, 116671, 265910,      1,      0],
       [123371,  80161, 268480,      0,      1],
       [146851,  96805, 286708,      1,      0],
       [115949,  93897, 299053,      0,      0],
       [155288,  88567,   4134,      1,      0],
       [115641,  784

array([[138671, 167497, 475918,      1,      0],
       [153151, 164745, 448032,      0,      1],
       [102919, 155589, 412068,      0,      0],
       [120445, 146520, 387333,      1,      0],
       [ 93165, 144255, 370302,      0,      0],
       [101588, 134024, 366995,      1,      0],
       [148972, 136763, 131850,      0,      1],
       [147304, 132446, 328010,      0,      0],
       [150492, 122690, 315747,      1,      0],
       [110453, 125482, 309115,      0,      1],
       [112368, 104061, 233294,      0,      0],
       [ 93564, 102819, 253878,      0,      1],
       [129094,  96011, 253973,      0,      0],
       [137269,  94140, 256798,      0,      1],
       [158321, 122091, 260646,      0,      0],
       [124390, 116671, 265910,      1,      0],
       [123371,  80161, 268480,      0,      1],
       [146851,  96805, 286708,      1,      0],
       [115949,  93897, 299053,      0,      0],
       [155288,  88567,   4134,      1,      0],
       [115641,  784

In [136]:
y = Main_data['Profit'].values

In [137]:
y

array([202443.83, 201974.06, 201232.39, 193083.99, 176369.94, 167173.12,
       166304.51, 165934.6 , 162393.77, 159941.96, 156303.95, 154441.4 ,
       151767.52, 144489.35, 142784.65, 140099.04, 137174.93, 135552.37,
       134448.9 , 132958.86, 128656.03, 121495.02, 120534.25, 118915.99,
       118734.04, 117586.34, 115915.54, 115190.31, 113464.38, 111186.64,
       110119.59, 107665.56, 107609.84, 106960.92, 106894.8 , 106661.51,
       100890.19, 100131.14,  91411.06,  91187.76,  88421.91,  87980.83,
        81680.49,  79940.98,  75382.33,  75108.08,  59672.75,  52741.73,
        45855.41,  24863.4 ])

Step 3: Train_test_split

In [138]:
#Split the data into training and test datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

Step 4: Training the Model

In [139]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
MLR = LinearRegression()
MLR.fit(X_train, y_train)

LinearRegression()

In [140]:
#Print the constant and coeffcients
print(f'constant = {MLR.intercept_}')
print(f'coefficients = {MLR.coef_}')

constant = 51168.39042485767
coefficients = [ 3.01968165e-02  7.90840255e-01  3.10148566e-02 -1.58229418e+02
 -4.63028992e+02]


In [141]:
# Predicting the Test set results
y_predict = MLR.predict(X_test)

In [142]:
# Display actual and predicted values side by side
df = pd.DataFrame(data=y_test, columns=['y_test'])
df['y_predict'] = y_predict
df

y_test      y_predict
0   113464.38  114464.764722
1   154441.40  142718.884992
2   156303.95  144092.850078
3    87980.83   82766.774894
4   201232.39  190102.927619
5   115190.31  124731.310792
6    91411.06   76626.432613
7   107665.56  108586.968401
8   120534.25  124681.828086
9   176369.94  179549.506399
10  106960.92  106704.625400
11  106661.51   98222.671829
12  115915.54  121131.994055
13  106894.80  100601.189785
14  134448.90  138202.462501

In [143]:
# Predicting the sigle observation results. Here 1,0 represents that the city is Mumbai
singl_obs = [160349,134321,401400,1,0]
feature_array = np.array(singl_obs)
feature_array = feature_array.reshape(1, -1)
y_pred_single_obs = MLR.predict(feature_array)
round(float(y_pred_single_obs), 2)

174528.01

Step 5:Evaluate the Model

In [144]:
#Model Evaluation using R-Square
from sklearn import metrics
r_square = metrics.r2_score(y_test, y_predict)
print('R-Square Error:', r_square)

R-Square Error: 0.9358680970045717


In [145]:
# We have 5 column in Multiple Linear Regression Equation : Profit = a0+a1*Miscellaneous_Expenses+a2*Food_Innovation_Spend+
# a3*Advertising+a4*Mumbai+a5*Tokyo
#Model Evaluation using Adjusted R-Square. 
# Here n = no. of observations and p = no. of independent variables
n = 50
p = 5
Adj_r_square = 1-(1-r_square)*(n-1)/(n-p-1)
print('Adjusted R-Square Error:', Adj_r_square)

Adjusted R-Square Error: 0.9285803807550912
